"""
GreenLedger - Carbon Footprint & Energy Calculation Engine
Provides transparent, auditable conversion from electrical power to carbon emissions.
Explicit unit conversion: Watts -> Kilowatts -> Kilowatt-Hours -> kg / grams CO2 equivalent.
"""

from typing import Dict, Any

# Default regional grid emission factor (US EPA eGRID average): 0.385 kg CO2e / kWh
DEFAULT_CARBON_INTENSITY = 0.385


def power_to_kwh(power_watts: float, duration_hours: float = 1.0) -> float:
    """Converts electrical power (Watts) sustained over a time period (Hours) into Kilowatt-Hours (kWh)."""
    if power_watts < 0.0 or duration_hours < 0.0:
        raise ValueError("Power and duration must be non-negative.")
    # (Watts / 1000 kW/W) * hours = kWh
    return (power_watts / 1000.0) * duration_hours


def kwh_to_co2(kwh: float, carbon_intensity_kg_per_kwh: float = DEFAULT_CARBON_INTENSITY) -> Dict[str, float]:
    """Converts energy consumption (kWh) into grams and kilograms of CO2 equivalent."""
    if kwh < 0.0 or carbon_intensity_kg_per_kwh < 0.0:
        raise ValueError("kWh and carbon intensity must be non-negative.")
    
    kg_co2 = kwh * carbon_intensity_kg_per_kwh
    g_co2 = kg_co2 * 1000.0
    
    # Standard environmental equivalencies:
    # 1 mature tree absorbs ~21,770 grams CO2 per year (~59.6 grams CO2 / day).
    # 1 average passenger vehicle emits ~120 grams CO2 / km.
    tree_days = g_co2 / 59.64
    car_km = g_co2 / 120.0

    return {
        "energy_kwh": round(kwh, 5),
        "emissions_kg_co2": round(kg_co2, 6),
        "emissions_g_co2": round(g_co2, 3),
        "trees_offset_equivalent": round(tree_days, 3),
        "car_km_equivalent": round(car_km, 3)
    }


def calculate_hourly_emissions(power_watts: float, carbon_intensity: float = DEFAULT_CARBON_INTENSITY) -> Dict[str, float]:
    """Calculates emissions generated by a device operating at power_watts for exactly 1 hour."""
    kwh = power_to_kwh(power_watts, 1.0)
    return kwh_to_co2(kwh, carbon_intensity)


def calculate_daily_emissions(power_watts: float, active_hours: float = 8.0, carbon_intensity: float = DEFAULT_CARBON_INTENSITY) -> Dict[str, float]:
    """Calculates estimated daily emissions for typical work operating hours."""
    kwh = power_to_kwh(power_watts, active_hours)
    return kwh_to_co2(kwh, carbon_intensity)


def calculate_savings(
    before_watts: float, 
    after_watts: float, 
    duration_hours: float = 1.0, 
    carbon_intensity: float = DEFAULT_CARBON_INTENSITY
) -> Dict[str, float]:
    """
    Computes delta in power and the resulting prevented carbon emissions over duration_hours.
    """
    delta_watts = max(0.0, before_watts - after_watts)
    pct_reduction = (delta_watts / before_watts * 100.0) if before_watts > 0 else 0.0
    kwh_saved = power_to_kwh(delta_watts, duration_hours)
    emissions_saved = kwh_to_co2(kwh_saved, carbon_intensity)

    return {
        "before_watts": round(before_watts, 2),
        "after_watts": round(after_watts, 2),
        "delta_watts": round(delta_watts, 2),
        "pct_reduction": round(pct_reduction, 2),
        "kwh_saved": emissions_saved["energy_kwh"],
        "co2_saved_g": emissions_saved["emissions_g_co2"],
        "co2_saved_kg": emissions_saved["emissions_kg_co2"]
    }
